import { StyleSheet } from "react-native";
import { colors } from "../constants/colors";

export const lightStyle = StyleSheet.create({
	itemContainer: {
		backgroundColor: colors.lightBackground,
		padding: 15,
		marginVertical: 6,
		marginHorizontal: 10,
		borderRadius: 40,
		shadowColor: colors.lightText,
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.05,
		shadowRadius: 3.84,
		elevation: 5,
	},
	itemHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
	},
	dayHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		fontSize: 18,
		backgroundColor: colors.primary,
		color: colors.white,
		paddingHorizontal: 15,
		paddingVertical: 10,
		marginVertical: 5,
		marginHorizontal: 10,
		borderRadius: 5,
		fontWeight: "bold",
	},
	title: {
		width: 200,
		fontSize: 20,
		color: colors.lightText,
	},
	addButton: {
		position: "absolute",
		bottom: 20,
		right: 20,
		width: 50,
		height: 50,
		backgroundColor: colors.buttonColor,
		borderRadius: 20,
		justifyContent: "center",
		alignItems: "center",
		elevation: 3,
		zIndex: 999,
	},
	div_for_hour_and_dropdownArrow: {
		marginLeft: 10,
		flex: 1,
		flexDirection: "row",
		justifyContent: "flex-end",
	},
	hour: {
		fontSize: 20,
		color: colors.lightText,
	},
	dropdown: {
		borderTopWidth: 3,
		borderTopStartRadius: 5,
		borderTopEndRadius: 5,
		borderTopColor: colors.darkText,
		padding: 10,
		flex: 1,
		flexDirection: "row",
		justifyContent: "space-around",
		marginTop: 20,
	},
	buttonContainer: {
		paddingHorizontal: 20,
		marginTop: 20,
		borderRadius: 10,
		backgroundColor: colors.lightAccent,
	},
});

export const darkStyle = StyleSheet.create({
	itemContainer: {
		backgroundColor: colors.darkBackground,
		color: colors.darkText,
		padding: 15,
		marginVertical: 6,
		marginHorizontal: 10,
		borderRadius: 5,
		shadowColor: colors.lightText,
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.05,
		shadowRadius: 3.84,
		elevation: 5,
	},
	itemHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		color: colors.darkText,
	},
	dayHeader: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		color: colors.darkText,
		fontSize: 28,
		backgroundColor: "#4A90E2",
		padding: 5,
		paddingHorizontal: 15,
		marginVertical: 5,
		marginHorizontal: 10,
		borderRadius: 5,
		fontWeight: "bold",
	},
	title: {
		width: 200,
		fontSize: 20,
		color: colors.darkText,
	},
	addButton: {
		position: "absolute",
		bottom: 20,
		right: 20,
		width: 50,
		height: 50,
		backgroundColor: colors.buttonColor,
		borderRadius: 20,
		justifyContent: "center",
		alignItems: "center",
		elevation: 3,
		zIndex: 999,
	},
	div_for_hour_and_dropdownArrow: {
		marginLeft: 10,
		flex: 1,
		flexDirection: "row",
		justifyContent: "flex-end",
	},
	hour: {
		fontSize: 20,
		color: colors.darkText,
	},
	dropdown: {
		borderTopWidth: 3,
		borderTopStartRadius: 5,
		borderTopEndRadius: 5,
		borderTopColor: colors.lightText,
		padding: 10,
		flex: 1,
		flexDirection: "row",
		justifyContent: "space-around",
		marginTop: 20,
	},
	buttonContainer: {
		paddingHorizontal: 20,
		marginTop: 20,
		borderRadius: 10,
		backgroundColor: colors.darkBackground,
	},
});

export const modalstyles = StyleSheet.create({
	centeredView: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		marginTop: 22,
	},
	modalView: {
		margin: 20,
		borderRadius: 20,
		padding: 35,
		alignItems: "center",
		opacity: 1,
		shadowColor: colors.lightText,
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.25,
		shadowRadius: 4,
		elevation: 5,
	},
	icon: {
		width: 24,
		height: 24,
		marginLeft: 5,
		marginTop: 3,
		color: colors.error,
	},
	button: {
		borderRadius: 20,
		padding: 10,
		elevation: 2,
	},
	textStyle: {
		color: colors.darkText,
		fontWeight: "bold",
		textAlign: "center",
	},
	modalText: {
		marginBottom: 15,
		textAlign: "center",
	},
});

export const floatingButtonStyles = StyleSheet.create({
	floatingButton: {
		position: 'absolute',
		bottom: 20,
		left: 20,
		width: 60,
		height: 60,
		borderRadius: 30,
		alignItems: 'center',
		justifyContent: 'center',
		elevation: 5,
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.8,
		shadowRadius: 2,
	},
	lightButton: {
		backgroundColor: '#ff6347',
	},
	darkButton: {
		backgroundColor: '#1e90ff',
	},
	buttonText: {
		fontSize: 20,
		color: '#fff',
	},

	ConfigureModalOverlay: {
		flex: 1,
		backgroundColor: 'rgba(0,0,0,0.5)',
		justifyContent: 'center',
		alignItems: 'center',
		paddingVertical: 50,
	  },
	  ConfigureModalContainer: {
		width: '80%',               
		maxHeight: '80%',            
		backgroundColor: colors.darkBackground,
		borderRadius: 20,
		padding: 20,
		alignItems: 'center',
		justifyContent: 'flex-start', 
		elevation: 10,
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.8,
		shadowRadius: 5,
	  },
	  modalContent: {
		paddingBottom: 0,
	  },
	  modalText: {
		fontSize: 18,
		marginBottom: 1,
		marginRight: 1,    
		flexWrap: 'wrap',
		width: "90%",
		color: "white",
	  },
	  courseRow: {
		flexDirection: 'row',  
		alignItems: 'center',   
		width: '70%',        
		marginBottom: 10,
		justifyContent: 'flex-start',
		flex: 1,
		borderRadius: 25,
		paddingVertical: 15,
		paddingHorizontal: 13,
		backgroundColor: "rgb(129, 133, 137)",
	  },
	  checkboxStyle: {
    	alignSelf: 'flex-start',
  	},
});
